#!/bin/bash

# get script location
DIR=$(dirname $0)

# load env
if [ ! -r $DIR"/.env" ]; then
    echo "Error: Script's .env file could not be found. Exiting."
    exit 1
else
    source $DIR"/.env"
fi

# ensure that a repository name has been provided
if [ ! -n "$1" ]; then
    echo "Error: No GitHub repository name was provided. Exiting."
    exit 1
else
    GITHUB_REPOSITORY_NAME="$1"
fi

# ensure directory doesn't already exist
if [ -d $GITHUB_REPOSITORY_NAME ]; then
    echo "Error: A directory with the name \"$GITHUB_USERNAME\" already exists. Exiting."
    exit 1 
fi

echo "Creating repository \"$1\" for GitHub user \"$GITHUB_USERNAME\"."

# grab extra optional args
if [ -n "$2" ]; then
    GITHUB_REPOSITORY_DESCRIPTION="$2"
elif [ -n "$GITHUB_DEFAULT_REPOSITORY_DESCRIPTION" ]; then
    GITHUB_REPOSITORY_DESCRIPTION="$GITHUB_DEFAULT_REPOSITORY_DESCRIPTION"
else
    GITHUB_REPOSITORY_DESCRIPTION=""
fi

# send api request
curl -L \
    -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $GITHUB_BEARER_TOKEN" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    -u "$GITHUB_USERNAME" \
    https://api.github.com/user/repos \
    -d "{\"name\": \"$GITHUB_REPOSITORY_NAME\", \"description\": \"$GITHUB_REPOSITORY_DESCRIPTION\", \"homepage\": \"https://github.com\", \"private\": false}" \

# now setup the repo
git clone git@github.com:"$GITHUB_USERNAME"/"$GITHUB_REPOSITORY_NAME".git
cd $GITHUB_REPOSITORY_NAME

# create a README.md 
echo "# "$GITHUB_REPOSITORY_NAME"" > README.md
git add README.md

# use the toptal gitgnore.io API to generate a .gitignore
curl -sS https://www.toptal.com/developers/gitignore/api/vim,linux,macos > .gitignore
git add .gitignore

# copy the MIT license TODO
#curl -d "{ \"copyright\": \"$LICENSE_COPYRIGHT\" }" https://rem.mit-license.org > LICENSE.md
#git add LICENSE.md

git commit -m 'GitHub repository automatically generated by create-github-repo.sh.'
git branch -M main
git push -u origin main
git checkout -b dev
